[versions]
android-compileSdk = "36"
android-minSdk = "26"
android-targetSdk = "36"
agp = "8.13.0"
kotlin = "2.2.20"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.9.4"
activityCompose = "1.11.0"
composeBom = "2025.10.00"
jetbrainsKotlinJvm = "2.2.20"
appcompat = "1.7.1"
material = "1.13.0"
hilt = "2.57.1"
room = "2.8.2"
ksp = "2.2.20-2.0.4"
roomKtx = "2.8.2"
retrofit = "3.0.0"
okhttp = "5.2.1"
logger ="5.2.1"
hilt_vm = "1.3.0"
uiController = "0.20.3"
composeMaterial = "1.5.5"
navigationCompose = "2.9.6"
paging = "3.3.6"
android-coroutines = "1.10.2"
pagingCommon = "3.3.6"
pagingCommonJvm = "3.3.6"
uiGraphics = "1.9.3"
coil = "3.3.0"
serialization = "1.9.0"
adaptive = "1.1.0"
lifecycleViewmodelKtx = "2.9.4"
runtime = "1.9.3"
material3 = "1.4.0"
uiText = "1.9.3"
foundationLayout = "1.9.3"
foundation = "1.9.3"
constraintlayout = "1.1.1"
splashscreen = "1.2.0"
lottie = "6.7.1"
uiTooling = "1.9.4"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashscreen" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-viewmodel = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hilt_vm" }
accompanist-uiController = {group = "com.google.accompanist",name = "accompanist-systemuicontroller", version.ref = "uiController"}
material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil"}
coil-network = { group = "io.coil-kt.coil3", name ="coil-network-okhttp", version.ref = "coil"}
lottie = { group = "com.airbnb.android", name="lottie-compose", version.ref = "lottie"}
room = { group = "androidx.room", name="room-runtime", version.ref = "room"}
room_compiler = { group = "androidx.room", name ="room-compiler", version.ref = "room"}
room-paging = { group = "androidx.room", name ="room-paging", version.ref = "room"}
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "roomKtx" }
compose-paging = { group = "androidx.paging", name ="paging-compose", version.ref = "paging"}
compose-constraint= { group = "androidx.constraintlayout", name ="constraintlayout-compose", version.ref = "constraintlayout"}


network_retrofit = {group ="com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit"}
network_okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp"}
network_logger = { group = "com.squareup.okhttp3", name = "logging-interceptor"  ,version.ref = "logger"}
network_serialization = {group = "com.squareup.retrofit2", name ="converter-gson", version.ref = "retrofit"}
androidx-compose-material = { group = "androidx.wear.compose", name = "compose-material", version.ref = "composeMaterial" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "android-coroutines"}
androidx-paging-common = { group = "androidx.paging", name = "paging-common", version.ref = "pagingCommon" }
androidx-paging-common-jvm = { group = "androidx.paging", name = "paging-common-jvm", version.ref = "pagingCommonJvm" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics", version.ref = "uiGraphics" }

kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "serialization" }
androidx-compose-adaptive = { group = "androidx.compose.material3.adaptive", name = "adaptive", version.ref = "adaptive" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "runtime" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
androidx-compose-ui-text = { group = "androidx.compose.ui", name = "ui-text", version.ref = "uiText" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "foundationLayout" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling", version.ref = "uiTooling" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = {id = "com.google.dagger.hilt.android", version.ref = "hilt"}


